### ISSUE TITLE
metrix status is error! "requests":{"current":0,"total":103661,"success":102174}

### ISSUE THREAD

**Issue by haqiaolong** [iresty/Mio#8]
hi 
  Why not change requests current

**Comment by moonbingbing** [comment]
the 'current' is on the TODO list, not realized yet

2016-12-05 11:15 GMT+08:00 haqiaolong <notifications@github.com>:

**Comment by haqiaolong** [comment]
您好，这个问题什么时候可以修复啊？

**Comment by moonbingbing** [comment]
Maybe about two months, in my opinion this is not an emergency function. PR
is welcome

2016-12-08 10:51 GMT+08:00 haqiaolong <notifications@github.com>:

**Comment by haqiaolong** [comment]
好的。谢谢
